### PR TITLE
support for react 15

### LINKED ISSUE #5: Support for React 15.0.0-rc.2
http://facebook.github.io/react/blog/2016/03/16/react-v15-rc2.html

### PR DESCRIPTION
**Pull request by d7h**
Closes #5 

@karlbright Can you have a Look ? Thx!

### CODE REVIEW

**Comment by karlbright** [comment]
@d7h Sounds good. If you could fix up the breaking tests then I'll happily merge. :+1:

**Comment by d7h** [comment]
@karlbright ok, in this context i've updated all the dependencies

**Comment by karlbright** [comment]
Good job :+1:

**Comment by karlbright** [comment]
@d7h Just published 0.6.0 with this change

**Comment by d7h** [comment]
@karlbright Thx!

**Pull request merged**
