### PR TITLE
[React] Add support for 0.14.0-rc1

### PR DESCRIPTION
**Pull request by oliviertassinari**
See https://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html.

### CODE REVIEW

**Comment by oliviertassinari** [comment]
@karlbright Can you have a look? Thanks!

**Comment by tedpennings** [comment]
:+1: for this now that 0.14.0 is out

**Comment by tedpennings** [comment]
although it'd be good to drop the `-rc` part of the 0.14.0 dependency string

**Comment by karlbright** [comment]
Currently looking in to this as the way context is handled within components is now different.

**Comment by karlbright** [comment]
@tedpennings @oliviertassinari Master is now updated for 0.14 and tests passing. Internal context was being stored differently and the tests could probably do without looking into internal context and just test output, but it works :ok_hand:

**Comment by tedpennings** [comment]
Thank you @karlbright  !
thank you

**Pull request closed without merging**
